[[main]]
name = "关于"
url = "/#about"
weight = 2

[[main]]
name = "简历"
url = "/files/JenniferShiyueZhang_CV_Jan2026.pdf"
weight = 3

[[main]]
name = "科研"
url = "/research/"
weight = 4

[[main]]
name = "教学"
url = "/teaching/"
weight = 5

# [[main]]
# name = "Skills"
# url = "/#skills"
# weight = 3

# [[main]]
# name = "Experience"
# url = "/#experience"
# weight = 4

[[main]]
name = "联系方式"
url = "/#contact"
weight = 6

# [[main]]
# name = "Tech Stack"
# url = "/#technical"
# weight = 4.5
#
# [[main]]
# name = "Blog"
# url = "/blog/"
# weight = 60
#
# [[main]]
# name = "Engineering"
# url = "/engineering/"
# weight = 50
# pre = "engineering"
#
# [[main]]
# name = "Contributions"
# url = "/contributions/"
# weight = 51
# pre = "contributions"
